/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. Never touches the database, so a sleeping Neon cannot fail it.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: one uncached round trip to the serving warehouse.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Anomalies
         * @description Every city on one day, with its departure and, where fitted, its rarity.
         */
        get: operations["anomalies_v1_anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/climate-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Climate Matrix
         * @description Every city crossed with every year: hot, cold and net anomaly days.
         */
        get: operations["climate_matrix_v1_climate_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description The dated extremes the validation gate checks, from the city registry.
         */
        get: operations["events_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk-horizon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Risk Horizon
         * @description The latest seven-day forecast for every registered city, scored or not.
         */
        get: operations["risk_horizon_v1_risk_horizon_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description How fresh the serving tier is.
         */
        get: operations["status_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storm-dynamics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Storm Dynamics
         * @description City-days of peak gust against the largest 24-hour pressure change.
         */
        get: operations["storm_dynamics_v1_storm_dynamics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Theme
         * @description The palette, from the one module that measured it.
         */
        get: operations["theme_v1_theme_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyCity */
        AnomalyCity: {
            /** Anomaly Z Critical */
            anomaly_z_critical: number | null;
            /** Baseline C */
            baseline_c: number | null;
            /** Baseline Observations */
            baseline_observations: number | null;
            /** Baseline Sigma */
            baseline_sigma: number | null;
            /** City Id */
            city_id: string;
            /** Country */
            country: string;
            /** Departure C */
            departure_c: number | null;
            /** Is Anomaly */
            is_anomaly: boolean | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Observed */
            observed: boolean;
            /** Observed C */
            observed_c: number | null;
            /** Return Is Reportable */
            return_is_reportable: boolean | null;
            /** Return Qualifier */
            return_qualifier: string | null;
            /** Return Years */
            return_years: number | null;
            /** Tail Fitted */
            tail_fitted: boolean;
            /** Z */
            z: number | null;
        };
        /** AnomalyDay */
        AnomalyDay: {
            /** Cities */
            cities: components["schemas"]["AnomalyCity"][];
            /** City Coverage */
            city_coverage: components["schemas"]["CityCoverage"][];
            coverage: components["schemas"]["Coverage"];
            /**
             * Day
             * Format: date
             */
            day: string;
        };
        /** Chrome */
        Chrome: {
            /** Axis */
            axis: string;
            /** Gridline */
            gridline: string;
            /** Ink */
            ink: string;
            /** Ink Muted */
            ink_muted: string;
            /** Ink Secondary */
            ink_secondary: string;
            /** Plane */
            plane: string;
            /** Surface */
            surface: string;
        };
        /** CityCoverage */
        CityCoverage: {
            /** City Id */
            city_id: string;
            /**
             * First Day
             * Format: date
             */
            first_day: string;
            /**
             * Last Day
             * Format: date
             */
            last_day: string;
            /** Observed Days */
            observed_days: number;
            /** Scored Days */
            scored_days: number;
        };
        /** CityTrend */
        CityTrend: {
            /** City Id */
            city_id: string;
            /** Cold */
            cold: number | null;
            /**
             * Hot
             * @description Hot anomaly days per decade; null below the year minimum.
             */
            hot: number | null;
            /** Name */
            name: string;
            /** Net */
            net: number | null;
        };
        /** ClimateMatrix */
        ClimateMatrix: {
            /** Cells */
            cells: components["schemas"]["MatrixCell"][];
            /** Count Breaks */
            count_breaks: number[];
            /** Count Labels */
            count_labels: string[];
            /** Min Trend Years */
            min_trend_years: number;
            /** Net Labels */
            net_labels: string[];
            /** Trends */
            trends: components["schemas"]["CityTrend"][];
        };
        /** Coverage */
        Coverage: {
            /** First Day */
            first_day: string | null;
            /** Last Day */
            last_day: string | null;
            /** Last Scored Day */
            last_scored_day: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MatrixCell */
        MatrixCell: {
            /** City Id */
            city_id: string;
            /** Cold Days */
            cold_days: number;
            /** Hot Days */
            hot_days: number;
            /** Name */
            name: string;
            /** Net Days */
            net_days: number;
            /**
             * Scored
             * @description False where the backfill has not reached this city-year.
             */
            scored: boolean;
            /** Scored Days */
            scored_days: number;
            /** Year */
            year: number;
        };
        /** ModePalette */
        ModePalette: {
            chrome: components["schemas"]["Chrome"];
            /**
             * Diverging
             * @description Nine steps, cold pole first.
             */
            diverging: string[];
            /** Emphasis */
            emphasis: string;
            /**
             * Risk
             * @description Five risk steps, lowest first.
             */
            risk: string[];
            /** @description Five counting steps each, lowest first. */
            sequential: components["schemas"]["Sequential"];
        };
        /** Ready */
        Ready: {
            /** Database */
            database: string;
            /** Host */
            host: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** RiskCity */
        RiskCity: {
            /** City Id */
            city_id: string;
            /** Country */
            country: string;
            /** Decision Threshold */
            decision_threshold: number | null;
            /** Feature Count */
            feature_count: number | null;
            /** Forecast Date */
            forecast_date: string | null;
            /** Horizon Days */
            horizon_days: number | null;
            /** Horizon End */
            horizon_end: string | null;
            /** Horizon Start */
            horizon_start: string | null;
            /** Model Variant */
            model_variant: string | null;
            /** Model Version */
            model_version: string | null;
            /** Name */
            name: string;
            /** Prediction Label */
            prediction_label: boolean | null;
            /** Risk Score */
            risk_score: number | null;
            /** Scored At */
            scored_at: string | null;
        };
        /** RiskDay */
        RiskDay: {
            /** City Id */
            city_id: string;
            /** Horizon Day */
            horizon_day: number;
            /**
             * Horizon Start
             * Format: date
             */
            horizon_start: string;
            /** Model Version */
            model_version: string | null;
            /** Risk Score */
            risk_score: number;
        };
        /** RiskHorizon */
        RiskHorizon: {
            /** Cities */
            cities: components["schemas"]["RiskCity"][];
            /**
             * Days
             * @description Per-day hazards; empty on a warehouse scored before ML-13.
             */
            days: components["schemas"]["RiskDay"][];
        };
        /** Sequential */
        Sequential: {
            /** Cold */
            cold: string[];
            /** Hot */
            hot: string[];
        };
        /** Status */
        Status: {
            /** Cities */
            cities: number;
            /** Database */
            database: string;
            /** Latest Forecast */
            latest_forecast: string | null;
            /** Latest Observation */
            latest_observation: string | null;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** StormDay */
        StormDay: {
            /** City Id */
            city_id: string;
            /**
             * Date Key
             * Format: date
             */
            date_key: string;
            /** Hours */
            hours: number;
            /** Name */
            name: string;
            /** Peak Gust */
            peak_gust: number;
            /** Pressure Change 24H */
            pressure_change_24h: number;
            /** Sharpest Fall */
            sharpest_fall: number;
            /** Sharpest Rise */
            sharpest_rise: number;
        };
        /** Theme */
        Theme: {
            /** Anomaly Breaks */
            anomaly_breaks: number[];
            /** Anomaly Z Threshold */
            anomaly_z_threshold: number;
            dark: components["schemas"]["ModePalette"];
            light: components["schemas"]["ModePalette"];
            /** Neutral Index */
            neutral_index: number;
            /** Risk Breaks */
            risk_breaks: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationEvent */
        ValidationEvent: {
            /** City */
            city: string;
            /** City Id */
            city_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            /** Direction */
            direction: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
        };
    };
    anomalies_v1_anomalies_get: {
        parameters: {
            query?: {
                /** @description Defaults to the last scored day. */
                day?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyDay"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    climate_matrix_v1_climate_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClimateMatrix"];
                };
            };
        };
    };
    events_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationEvent"][];
                };
            };
        };
    };
    risk_horizon_v1_risk_horizon_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskHorizon"];
                };
            };
        };
    };
    status_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    storm_dynamics_v1_storm_dynamics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDay"][];
                };
            };
        };
    };
    theme_v1_theme_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"];
                };
            };
        };
    };
}
